<?php

namespace App\Controller;

use App\Entity\Property;
use App\Form\CreatePropertyFormType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use phpDocumentor\Reflection\Types\Void_;
use Symfony\Component\Security\Core\User\UserInterface;

class PropertyController extends AbstractController
{
    /**
     * Fetch all the properties within the database and send them to the view to be showed the the user
     * @return Response
     * @Route("/properties", name="app_properties")
     */
    public function properties() : Response
    {

        $properties = $this->getDoctrine()
            ->getRepository(Property::class)
            ->findAll();


        if (!$properties) {
            throw $this->createNotFoundException(
                'No property has been found'
            );
        }

        return $this->render('property/properties.html.twig', [
            'properties' => $properties
        ]);
    }

    /**
     * Fetch the right property using the property id
     * @return Response
     * @Route("/properties/{id}", name="app_properties_entry")
     */
    public function property(int $id)
    {
        $entityManager = $this->getDoctrine()->getManager();

        $property = $entityManager->getRepository(Property::class)
            ->find($id);

        if (!$property) {
            throw $this->createNotFoundException('The given id is wrong');
        }

        return $this->render('property/property.html.twig', ['property' => $property]);
    }

    /**
     * @Route("/property/search", name="search_property")
     */
    
    public function searchProperty(Request $request){
        $properties = $this->getDoctrine()->getRepository(Property::class)->createQueryBuilder('p')
        ->where('p.name like :q')
        ->setParameter('q', '%' . $request->get("search_form")['q'] . '%')
        ->getQuery()
        ->getResult();
        
        return $this->render('property/search.html.twig', [
            'q' => $request->query->get("search_form")['q'],
            'properties' => $properties
        ]);
    }

    /**
     * @Route("/property/create", name="create_property")
     */
    public function createProperty(Request $request, UserInterface $user): Response
    {
        $property = new Property();
        $form = $this->createForm(CreatePropertyFormType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $files = $property->getPictures();
            $newNames = [];

            foreach ($files as $key => $file) {
                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('property_pictures_directory'),
                        $fileName
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                array_push($newNames, $fileName);
            }

            $property->setPictures($newNames);
            $property->setUser($user);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($property);

            if (!in_array('ROLE_HOTE', $user->getRoles())) {
                $user->setRoles(['ROLE_HOTE']);
                $entityManager->persist($user);
            }


            $entityManager->flush();

            return $this->redirectToRoute('app_properties');
        }

        return $this->render('property/create.html.twig', [
            'createPropertyForm' => $form->createView(),
        ]);
    }

    /**
     * Generate a unique file name
     * @return string
     */
     private function generateUniqueFileName() :string
     {
         // md5() reduces the similarity of the file names generated by
         // uniqid(), which is based on timestamps
         return md5(uniqid());
     }
}
