<?php

namespace App\Controller;

use App\Entity\Property;
use App\Form\CreatePropertyFormType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use phpDocumentor\Reflection\Types\Void_;
use Symfony\Component\Security\Core\User\UserInterface;

class PropertyController extends AbstractController
{
    /**
     * Fetch all the properties within the database and send them to the view to be showed the the user
     * @return Response
     * @Route("/properties", name="app_properties")
     */
    public function properties() : Response
    {

        $properties = $this->getDoctrine()
            ->getRepository(Property::class)
            ->findAll();


        if (!$properties) {
            throw $this->createNotFoundException(
                'No property has been found'
            );
        }

        return $this->render('property/properties.html.twig', [
            'properties' => $properties
        ]);
    }
    /**
     * @Route("/property/create", name="create_property")
     */
    public function createProperty(Request $request, UserInterface $user): Response
    {
        $property = new Property();
        $form = $this->createForm(CreatePropertyFormType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $files = $property->getPictures();
            $newNames = [];

            foreach ($files as $key => $file) {
                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('property_pictures_directory'),
                        $fileName
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                array_push($newNames, $fileName);
            }

            $property->setPictures($newNames);
            $property->setUser($user);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($property);
            $entityManager->flush();

            return $this->redirectToRoute('property');
        }

        return $this->render('property/create.html.twig', [
            'createPropertyForm' => $form->createView(),
        ]);
    }

    /**
     * Generate a unique file name
     * @return string
     */
     private function generateUniqueFileName() :string
     {
         // md5() reduces the similarity of the file names generated by
         // uniqid(), which is based on timestamps
         return md5(uniqid());
     }
}
